<?php
/**
 * @file
 * acc_import_panel.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function acc_import_panel_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-acc_export_taxonomy_terms-field_xls_url'
  $field_instances['node-acc_export_taxonomy_terms-field_xls_url'] = array(
    'bundle' => 'acc_export_taxonomy_terms',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'link',
        'settings' => array(),
        'type' => 'link_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_xls_url',
    'label' => 'XLS URL',
    'required' => FALSE,
    'settings' => array(
      'attributes' => array(
        'class' => '',
        'rel' => '',
        'target' => 'default',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'entity_translation_sync' => FALSE,
      'title' => 'optional',
      'title_maxlength' => 128,
      'title_value' => '',
      'url' => 0,
      'user_register_form' => FALSE,
      'validate_url' => 1,
    ),
    'widget' => array(
      'module' => 'link',
      'settings' => array(),
      'type' => 'link_field',
      'weight' => 31,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('XLS URL');

  return $field_instances;
}
